apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

# Needed to create or delete Prometheus and Grafana subscriptions
- apiGroups:
  - "operators.coreos.com"
  resources:
  - "operatorgroups"
  - "subscriptions"
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - list
  - create
  - get
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - create
  - get
  - list
  - watch
# Pelorus require new role to allow installplan approval job
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "roles"
  - "rolebindings"
  verbs:
  - create
  - get
  - list
  - watch
# Required to grand permissions to the installplan-approver user
- apiGroups:
  - "operators.coreos.com"
  resources:
  - "installplans"
  - "subscriptions"
  verbs:
  - get
  - list
  - patch
# Required to grand permissions to the csv-deleter / attempting to grant RBAC permissions not currently held
- apiGroups:
  - "operators.coreos.com"
  resources:
  - "clusterserviceversions"
  verbs:
  - delete
  - list


##
## Rules for charts.pelorus.konveyor.io/v1alpha1, Kind: PelorusOperators
##
- apiGroups:
  - charts.pelorus.konveyor.io
  resources:
  - pelorusoperators
  - pelorusoperators/status
  - pelorusoperators/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

#+kubebuilder:scaffold:rules
